# Custom nav
nav:
  title: "Binhan Bai"

favicon: ""

# Custom background
background:
  color: "#eff0f6"
  # image: "https://images.unsplash.com/photo-1502888395188-799b90b43871?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=fill&w=2700&q=80"
# Social media
social:
  WeiBo: https://weibo.com/u/2079293977
  JianShu: https://www.jianshu.com/u/65c591a20c38
  Instagram: https://www.instagram.com/binhanbai/
  GitHub: https://github.com/BBHNation

# Custom footer
mail: baibinhan.life@gmail.com
copyright: All rights reserved @Hancock Bai

# Custom menu. You can specific the path or the card style (only useful for category page).
# Two kinds of card style: 'project-card', 'article-card',
# Never mind the name.
menu:
  # Project:
  #   path: /categories/Projects
  #   card: project-card
  # Stuffs:
    # path: /tags/Stuffs
    # card: article-card
  Home: /
  Archive: /archives
  Categories: /categories
  About: https://github.com/BBHNation

# Specific default categories or tags of home page.
# Post which belongs to `category` or `tag` and don't belongs to `except_category` or `except_tag` will be filtered.
home:
  # set card style of home page
  # category: Projects
  # tag: 算法
  # except_category: 树
  # except_tag:
  #   - 总结
  #   - css

card_style:
  home: project-card
  archive: article-card
  tag: article-card
  category: article-card

# category page
category_generator:
  category_per_page: 3
  post_per_category: 3

node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false


# Show PV/UV of the website/page with busuanzi.
# Get more information on http://ibruce.info/2015/04/04/busuanzi/
# 增加不算子访问数量统计
busuanzi_count:
  # count values only if the other configs are false
  enable: true
  # custom uv span for the whole site
  site_uv: true
  site_uv_header: <i class="fa fa-user"></i> 访问人数
  site_uv_footer:
  # custom pv span for the whole site
  site_pv: true
  site_pv_header: <i class="fa fa-eye"></i> 访问总量
  site_pv_footer: 次
  # custom pv span for one page only
  page_pv: true
  page_pv_header: <i class="fa fa-file-o"></i> 浏览
  page_pv_footer: 次